FROM openjdk:8u191-jdk-windowsservercore-ltsc2016

WORKDIR /Code
COPY target/AppPkg .
COPY entryPoint.bat .
ENTRYPOINT C:\\Code\\entryPoint.bat

#CMD POWERSHELL Write-Host EntryPoint executed ; \
#while ($true) { Start-Sleep -Seconds 300 }